### ISSUE TITLE
[birthdays] issue with multiple birthdays on one day

### ISSUE THREAD

**Issue by coltoutram** [ZeLarpMaster/ZeCogsV3#11]
![](https://i.coltoutram.nl/9QL1j.png)

**Comment by coltoutram** [comment]
Basically re-mentioned the 1st person with a birthday

**Comment by ZeLarpMaster** [comment]
I'm not sure what's the issue here. Was it not those people's birthday?

What do you mean by "re-mentioned the 1st person"?

**Comment by coltoutram** [comment]
Two people's birthday today and this is what it looked like:

Its User A's birthday today!
User A is now 22 years old!

Its User B's birthday today!
User A is now 22 years old!

**Comment by ZeLarpMaster** [comment]
Ok ok, I'll take a look into that when I can. I've seen it happen too, but didn't have time to actually work on it. I'll prioritize it a bit more now that I know it happens to other people as well.

**Comment by coltoutram** [comment]
thanks

**Comment by thisisjvgrace** [comment]
yeah I was able to reproduce this easily. ZeLarp suggested me to open an issue here to keep track on its update but found this already open issue for this so posting this here.

Basically, when someone's birthday arrives, it posts the notification twice one after another in the set announcement channel. I'm owo#9494 on Discord btw.

**Comment by ZeLarpMaster** [comment]
I pushed a change which most likely fixes this issue. Please test again and confirm whether or not it's fixed.

**Comment by ZeLarpMaster** [comment]
Haven't heard back on it, I think it was fixed (I didn't see issues on my side) so I'll close this. Feel free to open a new one about it if the issue is still there.
