### ISSUE TITLE
Red Update

### ISSUE THREAD

**Issue by xNightWulf** [ZeLarpMaster/ZeCogsV3#13]
Birthdays and react_roles no longer work on the most updated version of red giving the error:

RuntimeError: The Birthdays cog in the birthdays.birthdays package does not inherit from the commands.Cog base class. The cog author must update the cog to adhere to this requirement.

and so on.

**Comment by ZeLarpMaster** [comment]
I think this has been fixed with #14 

Please confirm if that's the case or not. If it is, feel free to close the issue.
