### ISSUE TITLE
[react_roles] Not giving role on reaction [v3]

### ISSUE THREAD

**Issue by r3v0lution** [ZeLarpMaster/ZeCogsV3#2]
The cogs sets up fine and accepts the commands for message, emoji, and roles... But it never assigns the role.

I can run `!roles check etc..`  And it will assign the roles.  But `check` does not seem to remove roles if I click and remove the reaction.

Everything seemed to work fine on my v2 bot.

Any guidance would be appreciated.

**Comment by ZeLarpMaster** [comment]
Can you update your cog and see if you still have the issue?

**Comment by ZeLarpMaster** [comment]
No answer in the last 17 days. Closing.
