### ISSUE TITLE
[FEATURE REQUEST - Reminder] Command to delete reminders

### ISSUE THREAD

**Issue by Mystard** [ZeLarpMaster/ZeCogsV3#25]
Requesting delete functionality for reminders.

There have been quite a few times where I have created a reminder with bad syntax etc. and had to remake it.
Would be great to be able to remove these within Discord without editing the .json.

**Comment by ZeLarpMaster** [comment]
The latest version now has a forget all command. If you really need a command to remove a specific reminder, please let me know and I'll spend some time on it.
