### ISSUE TITLE
Consider adding your repository to unapproved repo list in Red-Index

### ISSUE THREAD

**Issue by jack1142** [ZeLarpMaster/ZeCogsV3#36]
Hello there!

I wanted to suggest you to add your repo to the unapproved repo list in [Red-Index](https://github.com/Cog-Creators/Red-Index). Red-Index is auto indexer of repositories and cogs for Red-DiscordBot with web interface (https://index.discord.red) and cog interface ([Index by Twentysix26](https://github.com/Twentysix26/x26-Cogs/)) that allow users to browse cogs with ease. We're very interested in expanding our list of unapproved repositories (as well as [getting new applications for approval](https://cogboard.red/c/apps/12), if you're interested in that 🙂) to ease the experience for Red users even more.

We accept PRs from repo authors that want to add their own repositories to the unapproved repository list.

Check it out:
https://github.com/Cog-Creators/Red-Index#red-index

**Comment by ZeLarpMaster** [comment]
[I've attempted it in the past](https://cogboard.red/t/rejected-zecogsv3/154), but was asked (in PMs) to rewrite all my cogs just to make them fit some arbitrary styling rules (I don't mind following pep8 though). I also don't spend much time on these cogs anymore so I don't want extra pressure to work on them from people who find my cogs on the index and I very much don't want to redo all my cogs just to get them approved.

**Comment by jack1142** [comment]
Making application for approval was just a brief mention in case you're interested, but I mostly wanted to suggest you to add the repo to unapproved repository list in the Index. There is no validation process for that so all you have to do is add an entry to the list of repositories and PR it, and it still adds some amount of visibility for the repo. And while we could technically just add unapproved repositories on our own, we agreed that it should be the repo owner who decides whether they want to include their repository in the list.

If you're still not interested in adding your repo to unapproved repository list, you can of course just close this issue and I won't be bothering you anymore :)
