### ISSUE TITLE
[voice_lock] [birthdays] Port cogs to V3

### ISSUE THREAD

**Issue by DerpDays** [ZeLarpMaster/ZeCogsV3#4]
Could you port over the cogs "Voice Lock" and "Birthdays" from your v2 repo and maybe add some of Saltie bots RL themed things (because i like rocketleague) like the price checker and the rep maybe the middleman one if my server becomes popular xD

**Comment by ZeLarpMaster** [comment]
The cogs from the Rocket League server which aren't public won't be public in part because someone who wants those features pretty much becomes a competitor of our server.

I'll work on voice lock and birthdays when I can

**Comment by ZeLarpMaster** [comment]
The "Birthdays" cog has been added to V3. "Voice Lock" is coming soon.

**Comment by DerpDays** [comment]
Soo any luck?

**Comment by ZeLarpMaster** [comment]
I'd prefer if you weren't applying pressure. I'll get to it when I can and asking for it again won't make things go faster.

I know it has been a long time, but I'm still looking at the issues whenever I have time to work on this.

**Comment by DerpDays** [comment]
Yeah sorry didn't mean for it to come out that way.

**Comment by DerpDays** [comment]
I guess ill try make one myself, i moved away from red anyway :*(
