### ISSUE TITLE
Error when loading birthdays 

### ISSUE THREAD

**Issue by sleepymanakete** [ZeLarpMaster/ZeCogsV3#7]
I got this error when trying to load birthdays. 
![image](https://user-images.githubusercontent.com/30272172/40734977-35dc0620-63f7-11e8-8a56-98f1f0081a5c.png)
If I try to install RedContext I get an error saying that it cant find RedContext.

**Comment by ZeLarpMaster** [comment]
RedContext is a part of redbot. It was moved in the latest update. I just need to update the code.

**Comment by sleepymanakete** [comment]
ah ok!

**Comment by sleepymanakete** [comment]
fixed, ty!
