### ISSUE TITLE
React_roles linked message IDs not exclusive

### ISSUE THREAD

**Issue by evacfk** [ZeLarpMaster/ZeCogsV3#8]
Steps I took. 

1. Linked 4 messages. 
2. Added reactions to each. 

Users can still select one of each role rather than just one total.

**Comment by ZeLarpMaster** [comment]
When you add new reactions with react_roles, it doesn't check if it's already linked or not. While I will change this behavior, you can fix this temporarily by adding the reactions first and then linking the messages.

**Comment by chnaski** [comment]
Evac, sometimes i have to restart my bot

**Comment by evacfk** [comment]
Works with the way you mentioned ZeLarpMaster, if that is the intended use then please close this and that's my mistake.

I assumed you would link messages first then add reactions, my apologies.
