### ISSUE TITLE
[react_roles] Error on bulk delete

### ISSUE THREAD

**Issue by coltoutram** [ZeLarpMaster/ZeCogsV3#9]
https://i.coltoutram.nl/MOC95.png

This error shows up in my console every time I do !cleanup messages <any number>, bulk deleting messages, not sure what causes it?

**Comment by coltoutram** [comment]
How come reactroles checks for message deletes anyways?

**Comment by ZeLarpMaster** [comment]
If a message which contains reactions with bound roles, it removes those roles from the config file to prevent the warning messages.

**Comment by coltoutram** [comment]
Ok, but how come everytime I do a bulk message delete using `cleanup messages` it throws out an error now though?

**Comment by ZeLarpMaster** [comment]
I don't know, I didn't have time to look into it yet

**Comment by ZeLarpMaster** [comment]
Should be fixed with the latest version. Please update the cog and tell me if it's fixed for you too.

**Comment by coltoutram** [comment]
Sorry for the late response, I was on holiday. Yes its fixed now, thank you.
